### ISSUE TITLE
Error trying to deploy 

### ISSUE THREAD

**Issue by AlexOsinaga** [srtaseen/3d-portfolio-website#1]
Tied to deploy this project in vercel but I've got the following error:

Failed to compile.
./components/ScrollModelAnimation.tsx:173:17
Type error: Property 'appendChild' does not exist on type 'never'.

![image](https://user-images.githubusercontent.com/38478044/200967896-659650a6-2046-4ec5-a80b-b8395744758c.png)

**Comment by AlexOsinaga** [comment]
i;m also having this error 
![image](https://user-images.githubusercontent.com/38478044/201502130-d22e09af-0110-458b-acaa-37bc0f7f05f0.png)

**Comment by srtaseen** [comment]
It's a typescript error, just replace the file extension .tsx to js
(ScrollModelAnimation.js). Hope it works this time.

**Comment by AlexOsinaga** [comment]
thank you very much it's working now
